; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = teensy41

[env:teensy41]
platform = teensy@5.1.0
board = teensy41
framework = arduino
platform_packages = 
	platformio/framework-arduinoteensy@1.162.0
	platformio/toolchain-gccarmnoneeabi-teensy@1.150201.0
board_build.f_cpu = 600000000L
extra_scripts =
	post:scripts/mp3_flash.py
	post:scripts/copy_firmware.py
	post:scripts/memory_usage.py
lib_deps = 
	https://github.com/mackron/dr_libs.git#dfe8377631000664666519fdb83da193fd8037f4
	adafruit/Adafruit GFX Library@^1.11.5
	adafruit/Adafruit MCP23017 Arduino Library@^2.3.2
	kurte/ILI9341_t3n@0.0.0-alpha+sha.f1bfb81825
build_flags = -D TEENSY_OPT_FASTEST
	-I include
	-Wall
	-Ilib -Isrc
	-std=gnu++20
lib_ldf_mode = deep+

[env:teensy41_calibration]
extends = env:teensy41
build_flags = ${env:teensy41.build_flags}
	-D LILLA_READ_BENCHMARK
