---
config:
  layout: elk
  flowchart:
    curve: basis
---
flowchart TB
  playersManager["Players_Manager"]
  player0["Player[0]"]
  adsr0["ADSR[0]"]
  vcf0["VCF[0]"]
  lfoP0["LFO_P0[0]"]
  playersStats["Players_statistics"]
  player1["Player[1]"]
  adsr1["ADSR[1]"]
  vcf1["VCF[1]"]
  lfoP1["LFO_P0[1]"]
  player2["Player[2]"]
  adsr2["ADSR[2]"]
  vcf2["VCF[2]"]
  lfoP2["LFO_P0[2]"]
  player3["Player[3]"]
  adsr3["ADSR[3]"]
  vcf3["VCF[3]"]
  lfoP3["LFO_P0[3]"]
  player4["Player[4]"]
  adsr4["ADSR[4]"]
  vcf4["VCF[4]"]
  lfoP4["LFO_P0[4]"]
  player5["Player[5]"]
  adsr5["ADSR[5]"]
  vcf5["VCF[5]"]
  lfoP5["LFO_P0[5]"]
  player6["Player[6]"]
  adsr6["ADSR[6]"]
  vcf6["VCF[6]"]
  lfoP6["LFO_P0[6]"]
  player7["Player[7]"]
  adsr7["ADSR[7]"]
  vcf7["VCF[7]"]
  lfoP7["LFO_P0[7]"]
  player8["Player[8]"]
  adsr8["ADSR[8]"]
  vcf8["VCF[8]"]
  lfoP8["LFO_P0[8]"]
  player9["Player[9]"]
  adsr9["ADSR[9]"]
  vcf9["VCF[9]"]
  lfoP9["LFO_P0[9]"]
  player10["Player[10]"]
  adsr10["ADSR[10]"]
  vcf10["VCF[10]"]
  lfoP10["LFO_P0[10]"]
  player11["Player[11]"]
  adsr11["ADSR[11]"]
  vcf11["VCF[11]"]
  lfoP11["LFO_P0[11]"]
  player12["Player[12]"]
  adsr12["ADSR[12]"]
  vcf12["VCF[12]"]
  lfoP12["LFO_P0[12]"]
  player13["Player[13]"]
  adsr13["ADSR[13]"]
  vcf13["VCF[13]"]
  lfoP13["LFO_P0[13]"]
  player14["Player[14]"]
  adsr14["ADSR[14]"]
  vcf14["VCF[14]"]
  lfoP14["LFO_P0[14]"]
  player15["Player[15]"]
  adsr15["ADSR[15]"]
  vcf15["VCF[15]"]
  lfoP15["LFO_P0[15]"]
  noclick0["Noclick[0]"]
  wavetable0["Wavetable[0]"]
  noclick1["Noclick[1]"]
  wavetable1["Wavetable[1]"]
  noclick2["Noclick[2]"]
  wavetable2["Wavetable[2]"]
  noclick3["Noclick[3]"]
  wavetable3["Wavetable[3]"]
  noclick4["Noclick[4]"]
  wavetable4["Wavetable[4]"]
  noclick5["Noclick[5]"]
  wavetable5["Wavetable[5]"]
  noclick6["Noclick[6]"]
  wavetable6["Wavetable[6]"]
  noclick7["Noclick[7]"]
  wavetable7["Wavetable[7]"]
  playersManager --> player0
  playersManager --> player0
  playersManager --> player0
  playersManager --> player0
  playersManager --> player0
  playersManager --> player0
  playersManager --> player0
  playersManager --> player0
  playersManager --> player0
  playersManager --> player0
  playersManager --> player0
  playersManager --> player0
  playersManager --> player0
  playersManager --> player0
  playersManager --> player0
  playersManager --> player0
  playersManager --> player0
  playersManager --> player0
  playersManager --> player0
  playersManager --> player0
  playersManager --> player0
  playersManager --> player0
  playersManager --> player0
  playersManager --> player0
  playersManager --> player0
  playersManager --> player0
  playersManager --> player0
  playersManager --> player0
  playersManager --> player0
  playersManager --> player0
  playersManager --> player0
  playersManager --> player0
  playersManager --> player0
  playersManager --> player0
  playersManager --> player0
  playersManager --> player0
  playersManager --> player0
  playersManager --> player0
  playersManager --> player0
  playersManager --> adsr0
  player0 --> adsr0
  player0 --> adsr0
  player0 --> adsr0
  player0 --> adsr0
  player0 --> adsr0
  player0 --> vcf0
  player0 --> vcf0
  player0 --> lfoP0
  player0 --> lfoP0
  player0 --> lfoP0
  player0 --> lfoP0
  player0 --> lfoP0
  player0 --> playersStats
  player0 --> playersStats
  player0 --> playersStats
  player0 --> playersStats
  playersManager --> player1
  playersManager --> player1
  playersManager --> player1
  playersManager --> player1
  playersManager --> player1
  playersManager --> player1
  playersManager --> player1
  playersManager --> player1
  playersManager --> player1
  playersManager --> player1
  playersManager --> player1
  playersManager --> player1
  playersManager --> player1
  playersManager --> player1
  playersManager --> player1
  playersManager --> player1
  playersManager --> player1
  playersManager --> player1
  playersManager --> player1
  playersManager --> player1
  playersManager --> player1
  playersManager --> player1
  playersManager --> player1
  playersManager --> player1
  playersManager --> player1
  playersManager --> player1
  playersManager --> player1
  playersManager --> player1
  playersManager --> player1
  playersManager --> player1
  playersManager --> player1
  playersManager --> player1
  playersManager --> player1
  playersManager --> player1
  playersManager --> player1
  playersManager --> player1
  playersManager --> player1
  playersManager --> player1
  playersManager --> player1
  playersManager --> adsr1
  player1 --> adsr1
  player1 --> adsr1
  player1 --> adsr1
  player1 --> adsr1
  player1 --> adsr1
  player1 --> vcf1
  player1 --> vcf1
  player1 --> lfoP1
  player1 --> lfoP1
  player1 --> lfoP1
  player1 --> lfoP1
  player1 --> lfoP1
  player1 --> playersStats
  player1 --> playersStats
  player1 --> playersStats
  player1 --> playersStats
  playersManager --> player2
  playersManager --> player2
  playersManager --> player2
  playersManager --> player2
  playersManager --> player2
  playersManager --> player2
  playersManager --> player2
  playersManager --> player2
  playersManager --> player2
  playersManager --> player2
  playersManager --> player2
  playersManager --> player2
  playersManager --> player2
  playersManager --> player2
  playersManager --> player2
  playersManager --> player2
  playersManager --> player2
  playersManager --> player2
  playersManager --> player2
  playersManager --> player2
  playersManager --> player2
  playersManager --> player2
  playersManager --> player2
  playersManager --> player2
  playersManager --> player2
  playersManager --> player2
  playersManager --> player2
  playersManager --> player2
  playersManager --> player2
  playersManager --> player2
  playersManager --> player2
  playersManager --> player2
  playersManager --> player2
  playersManager --> player2
  playersManager --> player2
  playersManager --> player2
  playersManager --> player2
  playersManager --> player2
  playersManager --> player2
  playersManager --> adsr2
  player2 --> adsr2
  player2 --> adsr2
  player2 --> adsr2
  player2 --> adsr2
  player2 --> adsr2
  player2 --> vcf2
  player2 --> vcf2
  player2 --> lfoP2
  player2 --> lfoP2
  player2 --> lfoP2
  player2 --> lfoP2
  player2 --> lfoP2
  player2 --> playersStats
  player2 --> playersStats
  player2 --> playersStats
  player2 --> playersStats
  playersManager --> player3
  playersManager --> player3
  playersManager --> player3
  playersManager --> player3
  playersManager --> player3
  playersManager --> player3
  playersManager --> player3
  playersManager --> player3
  playersManager --> player3
  playersManager --> player3
  playersManager --> player3
  playersManager --> player3
  playersManager --> player3
  playersManager --> player3
  playersManager --> player3
  playersManager --> player3
  playersManager --> player3
  playersManager --> player3
  playersManager --> player3
  playersManager --> player3
  playersManager --> player3
  playersManager --> player3
  playersManager --> player3
  playersManager --> player3
  playersManager --> player3
  playersManager --> player3
  playersManager --> player3
  playersManager --> player3
  playersManager --> player3
  playersManager --> player3
  playersManager --> player3
  playersManager --> player3
  playersManager --> player3
  playersManager --> player3
  playersManager --> player3
  playersManager --> player3
  playersManager --> player3
  playersManager --> player3
  playersManager --> player3
  playersManager --> adsr3
  player3 --> adsr3
  player3 --> adsr3
  player3 --> adsr3
  player3 --> adsr3
  player3 --> adsr3
  player3 --> vcf3
  player3 --> vcf3
  player3 --> lfoP3
  player3 --> lfoP3
  player3 --> lfoP3
  player3 --> lfoP3
  player3 --> lfoP3
  player3 --> playersStats
  player3 --> playersStats
  player3 --> playersStats
  player3 --> playersStats
  playersManager --> player4
  playersManager --> player4
  playersManager --> player4
  playersManager --> player4
  playersManager --> player4
  playersManager --> player4
  playersManager --> player4
  playersManager --> player4
  playersManager --> player4
  playersManager --> player4
  playersManager --> player4
  playersManager --> player4
  playersManager --> player4
  playersManager --> player4
  playersManager --> player4
  playersManager --> player4
  playersManager --> player4
  playersManager --> player4
  playersManager --> player4
  playersManager --> player4
  playersManager --> player4
  playersManager --> player4
  playersManager --> player4
  playersManager --> player4
  playersManager --> player4
  playersManager --> player4
  playersManager --> player4
  playersManager --> player4
  playersManager --> player4
  playersManager --> player4
  playersManager --> player4
  playersManager --> player4
  playersManager --> player4
  playersManager --> player4
  playersManager --> player4
  playersManager --> player4
  playersManager --> player4
  playersManager --> player4
  playersManager --> player4
  playersManager --> adsr4
  player4 --> adsr4
  player4 --> adsr4
  player4 --> adsr4
  player4 --> adsr4
  player4 --> adsr4
  player4 --> vcf4
  player4 --> vcf4
  player4 --> lfoP4
  player4 --> lfoP4
  player4 --> lfoP4
  player4 --> lfoP4
  player4 --> lfoP4
  player4 --> playersStats
  player4 --> playersStats
  player4 --> playersStats
  player4 --> playersStats
  playersManager --> player5
  playersManager --> player5
  playersManager --> player5
  playersManager --> player5
  playersManager --> player5
  playersManager --> player5
  playersManager --> player5
  playersManager --> player5
  playersManager --> player5
  playersManager --> player5
  playersManager --> player5
  playersManager --> player5
  playersManager --> player5
  playersManager --> player5
  playersManager --> player5
  playersManager --> player5
  playersManager --> player5
  playersManager --> player5
  playersManager --> player5
  playersManager --> player5
  playersManager --> player5
  playersManager --> player5
  playersManager --> player5
  playersManager --> player5
  playersManager --> player5
  playersManager --> player5
  playersManager --> player5
  playersManager --> player5
  playersManager --> player5
  playersManager --> player5
  playersManager --> player5
  playersManager --> player5
  playersManager --> player5
  playersManager --> player5
  playersManager --> player5
  playersManager --> player5
  playersManager --> player5
  playersManager --> player5
  playersManager --> player5
  playersManager --> adsr5
  player5 --> adsr5
  player5 --> adsr5
  player5 --> adsr5
  player5 --> adsr5
  player5 --> adsr5
  player5 --> vcf5
  player5 --> vcf5
  player5 --> lfoP5
  player5 --> lfoP5
  player5 --> lfoP5
  player5 --> lfoP5
  player5 --> lfoP5
  player5 --> playersStats
  player5 --> playersStats
  player5 --> playersStats
  player5 --> playersStats
  playersManager --> player6
  playersManager --> player6
  playersManager --> player6
  playersManager --> player6
  playersManager --> player6
  playersManager --> player6
  playersManager --> player6
  playersManager --> player6
  playersManager --> player6
  playersManager --> player6
  playersManager --> player6
  playersManager --> player6
  playersManager --> player6
  playersManager --> player6
  playersManager --> player6
  playersManager --> player6
  playersManager --> player6
  playersManager --> player6
  playersManager --> player6
  playersManager --> player6
  playersManager --> player6
  playersManager --> player6
  playersManager --> player6
  playersManager --> player6
  playersManager --> player6
  playersManager --> player6
  playersManager --> player6
  playersManager --> player6
  playersManager --> player6
  playersManager --> player6
  playersManager --> player6
  playersManager --> player6
  playersManager --> player6
  playersManager --> player6
  playersManager --> player6
  playersManager --> player6
  playersManager --> player6
  playersManager --> player6
  playersManager --> player6
  playersManager --> adsr6
  player6 --> adsr6
  player6 --> adsr6
  player6 --> adsr6
  player6 --> adsr6
  player6 --> adsr6
  player6 --> vcf6
  player6 --> vcf6
  player6 --> lfoP6
  player6 --> lfoP6
  player6 --> lfoP6
  player6 --> lfoP6
  player6 --> lfoP6
  player6 --> playersStats
  player6 --> playersStats
  player6 --> playersStats
  player6 --> playersStats
  playersManager --> player7
  playersManager --> player7
  playersManager --> player7
  playersManager --> player7
  playersManager --> player7
  playersManager --> player7
  playersManager --> player7
  playersManager --> player7
  playersManager --> player7
  playersManager --> player7
  playersManager --> player7
  playersManager --> player7
  playersManager --> player7
  playersManager --> player7
  playersManager --> player7
  playersManager --> player7
  playersManager --> player7
  playersManager --> player7
  playersManager --> player7
  playersManager --> player7
  playersManager --> player7
  playersManager --> player7
  playersManager --> player7
  playersManager --> player7
  playersManager --> player7
  playersManager --> player7
  playersManager --> player7
  playersManager --> player7
  playersManager --> player7
  playersManager --> player7
  playersManager --> player7
  playersManager --> player7
  playersManager --> player7
  playersManager --> player7
  playersManager --> player7
  playersManager --> player7
  playersManager --> player7
  playersManager --> player7
  playersManager --> player7
  playersManager --> adsr7
  player7 --> adsr7
  player7 --> adsr7
  player7 --> adsr7
  player7 --> adsr7
  player7 --> adsr7
  player7 --> vcf7
  player7 --> vcf7
  player7 --> lfoP7
  player7 --> lfoP7
  player7 --> lfoP7
  player7 --> lfoP7
  player7 --> lfoP7
  player7 --> playersStats
  player7 --> playersStats
  player7 --> playersStats
  player7 --> playersStats
  playersManager --> player8
  playersManager --> player8
  playersManager --> player8
  playersManager --> player8
  playersManager --> player8
  playersManager --> player8
  playersManager --> player8
  playersManager --> player8
  playersManager --> player8
  playersManager --> player8
  playersManager --> player8
  playersManager --> player8
  playersManager --> player8
  playersManager --> player8
  playersManager --> player8
  playersManager --> player8
  playersManager --> player8
  playersManager --> player8
  playersManager --> player8
  playersManager --> player8
  playersManager --> player8
  playersManager --> player8
  playersManager --> player8
  playersManager --> player8
  playersManager --> player8
  playersManager --> player8
  playersManager --> player8
  playersManager --> player8
  playersManager --> player8
  playersManager --> player8
  playersManager --> player8
  playersManager --> player8
  playersManager --> player8
  playersManager --> player8
  playersManager --> player8
  playersManager --> player8
  playersManager --> player8
  playersManager --> player8
  playersManager --> player8
  playersManager --> adsr8
  player8 --> adsr8
  player8 --> adsr8
  player8 --> adsr8
  player8 --> adsr8
  player8 --> adsr8
  player8 --> vcf8
  player8 --> vcf8
  player8 --> lfoP8
  player8 --> lfoP8
  player8 --> lfoP8
  player8 --> lfoP8
  player8 --> lfoP8
  player8 --> playersStats
  player8 --> playersStats
  player8 --> playersStats
  player8 --> playersStats
  playersManager --> player9
  playersManager --> player9
  playersManager --> player9
  playersManager --> player9
  playersManager --> player9
  playersManager --> player9
  playersManager --> player9
  playersManager --> player9
  playersManager --> player9
  playersManager --> player9
  playersManager --> player9
  playersManager --> player9
  playersManager --> player9
  playersManager --> player9
  playersManager --> player9
  playersManager --> player9
  playersManager --> player9
  playersManager --> player9
  playersManager --> player9
  playersManager --> player9
  playersManager --> player9
  playersManager --> player9
  playersManager --> player9
  playersManager --> player9
  playersManager --> player9
  playersManager --> player9
  playersManager --> player9
  playersManager --> player9
  playersManager --> player9
  playersManager --> player9
  playersManager --> player9
  playersManager --> player9
  playersManager --> player9
  playersManager --> player9
  playersManager --> player9
  playersManager --> player9
  playersManager --> player9
  playersManager --> player9
  playersManager --> player9
  playersManager --> adsr9
  player9 --> adsr9
  player9 --> adsr9
  player9 --> adsr9
  player9 --> adsr9
  player9 --> adsr9
  player9 --> vcf9
  player9 --> vcf9
  player9 --> lfoP9
  player9 --> lfoP9
  player9 --> lfoP9
  player9 --> lfoP9
  player9 --> lfoP9
  player9 --> playersStats
  player9 --> playersStats
  player9 --> playersStats
  player9 --> playersStats
  playersManager --> player10
  playersManager --> player10
  playersManager --> player10
  playersManager --> player10
  playersManager --> player10
  playersManager --> player10
  playersManager --> player10
  playersManager --> player10
  playersManager --> player10
  playersManager --> player10
  playersManager --> player10
  playersManager --> player10
  playersManager --> player10
  playersManager --> player10
  playersManager --> player10
  playersManager --> player10
  playersManager --> player10
  playersManager --> player10
  playersManager --> player10
  playersManager --> player10
  playersManager --> player10
  playersManager --> player10
  playersManager --> player10
  playersManager --> player10
  playersManager --> player10
  playersManager --> player10
  playersManager --> player10
  playersManager --> player10
  playersManager --> player10
  playersManager --> player10
  playersManager --> player10
  playersManager --> player10
  playersManager --> player10
  playersManager --> player10
  playersManager --> player10
  playersManager --> player10
  playersManager --> player10
  playersManager --> player10
  playersManager --> player10
  playersManager --> adsr10
  player10 --> adsr10
  player10 --> adsr10
  player10 --> adsr10
  player10 --> adsr10
  player10 --> adsr10
  player10 --> vcf10
  player10 --> vcf10
  player10 --> lfoP10
  player10 --> lfoP10
  player10 --> lfoP10
  player10 --> lfoP10
  player10 --> lfoP10
  player10 --> playersStats
  player10 --> playersStats
  player10 --> playersStats
  player10 --> playersStats
  playersManager --> player11
  playersManager --> player11
  playersManager --> player11
  playersManager --> player11
  playersManager --> player11
  playersManager --> player11
  playersManager --> player11
  playersManager --> player11
  playersManager --> player11
  playersManager --> player11
  playersManager --> player11
  playersManager --> player11
  playersManager --> player11
  playersManager --> player11
  playersManager --> player11
  playersManager --> player11
  playersManager --> player11
  playersManager --> player11
  playersManager --> player11
  playersManager --> player11
  playersManager --> player11
  playersManager --> player11
  playersManager --> player11
  playersManager --> player11
  playersManager --> player11
  playersManager --> player11
  playersManager --> player11
  playersManager --> player11
  playersManager --> player11
  playersManager --> player11
  playersManager --> player11
  playersManager --> player11
  playersManager --> player11
  playersManager --> player11
  playersManager --> player11
  playersManager --> player11
  playersManager --> player11
  playersManager --> player11
  playersManager --> player11
  playersManager --> adsr11
  player11 --> adsr11
  player11 --> adsr11
  player11 --> adsr11
  player11 --> adsr11
  player11 --> adsr11
  player11 --> vcf11
  player11 --> vcf11
  player11 --> lfoP11
  player11 --> lfoP11
  player11 --> lfoP11
  player11 --> lfoP11
  player11 --> lfoP11
  player11 --> playersStats
  player11 --> playersStats
  player11 --> playersStats
  player11 --> playersStats
  playersManager --> player12
  playersManager --> player12
  playersManager --> player12
  playersManager --> player12
  playersManager --> player12
  playersManager --> player12
  playersManager --> player12
  playersManager --> player12
  playersManager --> player12
  playersManager --> player12
  playersManager --> player12
  playersManager --> player12
  playersManager --> player12
  playersManager --> player12
  playersManager --> player12
  playersManager --> player12
  playersManager --> player12
  playersManager --> player12
  playersManager --> player12
  playersManager --> player12
  playersManager --> player12
  playersManager --> player12
  playersManager --> player12
  playersManager --> player12
  playersManager --> player12
  playersManager --> player12
  playersManager --> player12
  playersManager --> player12
  playersManager --> player12
  playersManager --> player12
  playersManager --> player12
  playersManager --> player12
  playersManager --> player12
  playersManager --> player12
  playersManager --> player12
  playersManager --> player12
  playersManager --> player12
  playersManager --> player12
  playersManager --> player12
  playersManager --> adsr12
  player12 --> adsr12
  player12 --> adsr12
  player12 --> adsr12
  player12 --> adsr12
  player12 --> adsr12
  player12 --> vcf12
  player12 --> vcf12
  player12 --> lfoP12
  player12 --> lfoP12
  player12 --> lfoP12
  player12 --> lfoP12
  player12 --> lfoP12
  player12 --> playersStats
  player12 --> playersStats
  player12 --> playersStats
  player12 --> playersStats
  playersManager --> player13
  playersManager --> player13
  playersManager --> player13
  playersManager --> player13
  playersManager --> player13
  playersManager --> player13
  playersManager --> player13
  playersManager --> player13
  playersManager --> player13
  playersManager --> player13
  playersManager --> player13
  playersManager --> player13
  playersManager --> player13
  playersManager --> player13
  playersManager --> player13
  playersManager --> player13
  playersManager --> player13
  playersManager --> player13
  playersManager --> player13
  playersManager --> player13
  playersManager --> player13
  playersManager --> player13
  playersManager --> player13
  playersManager --> player13
  playersManager --> player13
  playersManager --> player13
  playersManager --> player13
  playersManager --> player13
  playersManager --> player13
  playersManager --> player13
  playersManager --> player13
  playersManager --> player13
  playersManager --> player13
  playersManager --> player13
  playersManager --> player13
  playersManager --> player13
  playersManager --> player13
  playersManager --> player13
  playersManager --> player13
  playersManager --> adsr13
  player13 --> adsr13
  player13 --> adsr13
  player13 --> adsr13
  player13 --> adsr13
  player13 --> adsr13
  player13 --> vcf13
  player13 --> vcf13
  player13 --> lfoP13
  player13 --> lfoP13
  player13 --> lfoP13
  player13 --> lfoP13
  player13 --> lfoP13
  player13 --> playersStats
  player13 --> playersStats
  player13 --> playersStats
  player13 --> playersStats
  playersManager --> player14
  playersManager --> player14
  playersManager --> player14
  playersManager --> player14
  playersManager --> player14
  playersManager --> player14
  playersManager --> player14
  playersManager --> player14
  playersManager --> player14
  playersManager --> player14
  playersManager --> player14
  playersManager --> player14
  playersManager --> player14
  playersManager --> player14
  playersManager --> player14
  playersManager --> player14
  playersManager --> player14
  playersManager --> player14
  playersManager --> player14
  playersManager --> player14
  playersManager --> player14
  playersManager --> player14
  playersManager --> player14
  playersManager --> player14
  playersManager --> player14
  playersManager --> player14
  playersManager --> player14
  playersManager --> player14
  playersManager --> player14
  playersManager --> player14
  playersManager --> player14
  playersManager --> player14
  playersManager --> player14
  playersManager --> player14
  playersManager --> player14
  playersManager --> player14
  playersManager --> player14
  playersManager --> player14
  playersManager --> player14
  playersManager --> adsr14
  player14 --> adsr14
  player14 --> adsr14
  player14 --> adsr14
  player14 --> adsr14
  player14 --> adsr14
  player14 --> vcf14
  player14 --> vcf14
  player14 --> lfoP14
  player14 --> lfoP14
  player14 --> lfoP14
  player14 --> lfoP14
  player14 --> lfoP14
  player14 --> playersStats
  player14 --> playersStats
  player14 --> playersStats
  player14 --> playersStats
  playersManager --> player15
  playersManager --> player15
  playersManager --> player15
  playersManager --> player15
  playersManager --> player15
  playersManager --> player15
  playersManager --> player15
  playersManager --> player15
  playersManager --> player15
  playersManager --> player15
  playersManager --> player15
  playersManager --> player15
  playersManager --> player15
  playersManager --> player15
  playersManager --> player15
  playersManager --> player15
  playersManager --> player15
  playersManager --> player15
  playersManager --> player15
  playersManager --> player15
  playersManager --> player15
  playersManager --> player15
  playersManager --> player15
  playersManager --> player15
  playersManager --> player15
  playersManager --> player15
  playersManager --> player15
  playersManager --> player15
  playersManager --> player15
  playersManager --> player15
  playersManager --> player15
  playersManager --> player15
  playersManager --> player15
  playersManager --> player15
  playersManager --> player15
  playersManager --> player15
  playersManager --> player15
  playersManager --> player15
  playersManager --> player15
  playersManager --> adsr15
  player15 --> adsr15
  player15 --> adsr15
  player15 --> adsr15
  player15 --> adsr15
  player15 --> adsr15
  player15 --> vcf15
  player15 --> vcf15
  player15 --> lfoP15
  player15 --> lfoP15
  player15 --> lfoP15
  player15 --> lfoP15
  player15 --> lfoP15
  player15 --> playersStats
  player15 --> playersStats
  player15 --> playersStats
  player15 --> playersStats
  playersManager --> noclick0
  playersManager --> wavetable0
  playersManager --> noclick1
  playersManager --> wavetable1
  playersManager --> noclick2
  playersManager --> wavetable2
  playersManager --> noclick3
  playersManager --> wavetable3
  playersManager --> noclick4
  playersManager --> wavetable4
  playersManager --> noclick5
  playersManager --> wavetable5
  playersManager --> noclick6
  playersManager --> wavetable6
  playersManager --> noclick7
  playersManager --> wavetable7
  classDef mainNodeStyle fill:#193f5e,color:#fff,stroke:#102f49,stroke-width:3px
  classDef objectNodeStyle fill:#fff,color:#172b3a,stroke:#9cabb7,stroke-width:1px
  class playersManager,player0,adsr0,vcf0,lfoP0,playersStats,player1,adsr1,vcf1,lfoP1,player2,adsr2,vcf2,lfoP2,player3,adsr3,vcf3,lfoP3,player4,adsr4,vcf4,lfoP4,player5,adsr5,vcf5,lfoP5,player6,adsr6,vcf6,lfoP6,player7,adsr7,vcf7,lfoP7,player8,adsr8,vcf8,lfoP8,player9,adsr9,vcf9,lfoP9,player10,adsr10,vcf10,lfoP10,player11,adsr11,vcf11,lfoP11,player12,adsr12,vcf12,lfoP12,player13,adsr13,vcf13,lfoP13,player14,adsr14,vcf14,lfoP14,player15,adsr15,vcf15,lfoP15,noclick0,wavetable0,noclick1,wavetable1,noclick2,wavetable2,noclick3,wavetable3,noclick4,wavetable4,noclick5,wavetable5,noclick6,wavetable6,noclick7,wavetable7 objectNodeStyle
